# This is the default configuration file of BungeeTabListPlus.
#
# Since the configuration of the plugin is quite complex you
# might want to have a look at the wiki from time to time.
#
# Wiki: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki
#  Placeholders: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Placeholders
#  Examples: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Examples
#

# Configure who can see the tab lists
# See https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/MultipleTablists
showTo: "all"
priority: 0

# Configure header and footer
# See https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Configuration-Basics-Part-3---Header-and-Footer
showHeaderFooter: true
header:
  - "&c欢迎 &f${viewer name}"
headerAnimationUpdateInterval: 0.2
footer:
  - "&4"
  - "&4"
footerAnimationUpdateInterval: 5

# Custom placeholders are a powerful mechanism to add more dynamic content
# to the tab list.
# See https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/CustomPlaceholders
customPlaceholders:
  # Defines the ${afk_tag} placeholder which is used to add "|away"
  # to the players name if he is afk.
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: "&7|&o离开"
    false: ""
  # Defines the ${viewer_colored_ping} placeholder which adds a color code to
  # the ping using the following color scheme:
  # 0 - 49   -> green
  # 50 - 149 -> yellow
  # 150+     -> red
  viewer_colored_ping:
    !conditional
    condition: "${viewer ping} < 150"
    true: ${viewer_colored_ping0}
    false: "&c${viewer ping}"
  viewer_colored_ping0:
    !conditional
    condition: "${viewer ping} < 50"
    true: "&a${viewer ping}"
    false: "&e${viewer ping}"

# Player sets are required to display players and player counts on the tab list.
# See https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Configuration-Basics-Part-4---Player-sets
playerSets:
  all_players:
    filter: true

# Type of the tab list
# See https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Configuration-Basics-Part-5---Dynamic-Size-Tablist
# and https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Configuration-Basics-Part-6---Fixed-Size-Tablist-Introduction
# for different options
type: FIXED_SIZE
size: 60

defaultIcon: colors/dark_gray.png
defaultPing: 1000

# Here the content of the tab list is configured:
components:
  - {text: "&c服务器: &6${viewer server}", icon: "default/server.png", ping: 0}
  - {text: "&c等级: &6${viewer vault_primary_group}", icon: "default/rank.png", ping: 0}
  - {text: "&c网速: ${viewer_colored_ping}ms", icon: "default/ping.png", ping: 0}
  -
  -
  -
  - !players_by_server
    playerSet: all_players
    serverHeader:
      - {text: "&e&n${server}&f&o (${server_player_count}):", icon: "colors/yellow.png", ping: 0}
    serverSeparator:
      -
      -
      -
    showServers: ALL
    playerComponent: "${viewer luckperms_prefix}${player display_name}${afk_tag}"
    morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}
  - !spacer {}
  -
  -
  -
  - {text: "&c时间: &6${time H:mm:ss}", icon: "default/clock.png", ping: 0}
  - {text: "&c玩家数量: &6${playerset:all_players size}", icon: "default/players.png", ping: 0}
  - {text: "&c金钱: &6${viewer vault_balance 1.2}", icon: "default/balance.png", ping: 0}
